export const tastingOptions = {
  distilleries: ["Glenmorangie", "GlenDronach", "Aberlour", "The Glenlivet", "Balvenie"],
  heritage: {
    SCT: [
      "HL",
      "SS",
      "LL",
      "CP",
      "IL-IS",
      "IL-SK",
      "IL-O",
      "IS-A",
      "IS-M",
      "IS-J",
      "IS-L",
    ],
    GER: [
      "BW",
      "BY",
      "BE",
      "BB",
      "HB",
      "HH",
      "HE",
      "MV",
      "NI",
      "NW",
      "RP",
      "SL",
      "SN",
      "ST",
      "SH",
      "TH",
    ],
    USA: ["KY", "TN"],
    IRL: [],
    JPN: [],
    WAL: [],
    IND: [],
    ESP: [],
    CAN: [],
    POL: [],
    DNK: [],
    SWE: [],
    TWN: [],
    FRA: [],
  },
  kind: ["SM", "BLM", "BL", "BO", "R"],
  maturation: {
    SHERRY: ['OLOROSO', 'PEDRO XIMENEZ', 'FINO', 'AMONTILLADO', 'MANZANILLA'],
    WINE: ['CABERNET SAUVIGNON', "AMERONE", "BURGUNDY", "BANYUL"],
    MADEIRA: [],
    MARSALA: [],
    SAUTERNES: [],
    BOURBON: [],
    PORT: [],
    MALAGA: [],
    RUM: [],
    WOOD: ['WHITE-OAK', 'DARK-OAK'],
    BEER: [],
  }
};